Onboarding Screen Styles
0xsend/sendapp pull request #101
Opened 2024-02-01 23:58 UTC by youngkidwarrior

2024-02-01 23:59 UTC, youngkidwarrior commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/101?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #80** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/80?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #81** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/81?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #83** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/83?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #84** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/84?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #87** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/87?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #92** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/92?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #93** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/93?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                * **PR #94** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/94?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                  * **PR #95** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/95?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                    * **PR #96** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/96?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                      * **PR #99** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/99?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                        * **PR #101** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/101?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/0xsend/sendapp/101?utm_source=stack-comment).

2024-02-02 22:33 UTC, 0xBigBoss approved these changes
didn't visually check this one out, but LGTM

2024-02-02 22:33 UTC, 0xBigBoss commented on packages/app/features/onboarding/screen.tsx
thanks for starting on this one. Feel free to drop the "send demo" from `packages/playwright/tests/onboarding.logged-in.spec.ts`. I'm still tackling sending in my profiles PR.

2024-02-04 07:52 UTC, youngkidwarrior commented on packages/app/features/onboarding/screen.tsx
Removed, double check for me that I understood you correctly and didn't delete anything important

2024-02-04 20:42 UTC, 0xBigBoss requested changes

2024-02-04 20:42 UTC, 0xBigBoss commented on packages/playwright/tests/onboarding.logged-in.spec.ts
> -  await testBaseClient.setBalance({
Sorry, yeah you deleted too much. The "send" demo starts from this line and down. Perhaps, we move the checks above to the `OnboardingPage` fixture.

2024-02-04 20:42 UTC, 0xBigBoss commented on packages/app/features/onboarding/screen.tsx
> +          <SendAccountUserOp />
Let's drop this component entirely. This is the UI of the "send" demo I was referring to. It's no longer needed here.

Also drop the function here https://github.com/0xsend/sendapp/blob/99b109fb3aeb20ded846c52fa0583f560a145b88/packages/app/features/onboarding/screen.tsx#L179-L182

Then, for now, let's just show a paragraph or something similar. `Congratulations on opening your first Send Account! Let's get you sending, first, fund your account by sending ETH here ${address}`.

Could you screencap this `Congrats` part and post in design? We need to bring in Rit for that part of the design as well. 

You can add a `// @todo` here for above and just redirect to home page as well.

2024-02-04 21:00 UTC, youngkidwarrior commented on packages/app/features/onboarding/screen.tsx
> +          <SendAccountUserOp />
Can do

2024-02-05 00:04 UTC, youngkidwarrior commented on packages/playwright/tests/onboarding.logged-in.spec.ts
> -  await testBaseClient.setBalance({
Which checks, the send demo stuff or the webAuthn stuff

2024-02-05 01:48 UTC, youngkidwarrior commented on packages/app/features/onboarding/screen.tsx
> +          <SendAccountUserOp />
@0xBigBoss See #107

2024-02-05 17:17 UTC, 0xBigBoss approved these changes

2024-02-05 17:17 UTC, 0xBigBoss commented on packages/app/features/onboarding/screen.tsx
> +      <Input id="sendTo" aria-label="sendTo" value={receiverAccount.address} />
I think the x-platform way is [accessibilityLabel](https://reactnative.dev/docs/accessibility#accessibilitylabel), but maybe tamagui sets this up for us automatically. 🤷

2024-02-05 17:17 UTC, 0xBigBoss commented on packages/playwright/tests/onboarding.logged-in.spec.ts
> -  await testBaseClient.setBalance({
Sorry, I wasn't more specific. This changset looks good. I don't think we can refactor the `expect`'s above this line.

2024-02-08 18:24 UTC, youngkidwarrior commented
### Merge activity

* **Feb 8, 1:24 PM EST**: [Graphite](https://app.graphite.dev/github/pr/0xsend/sendapp/101) rebased this pull request after merging its parent, because this pull request is set to merge when ready.

2024-02-08 18:37 UTC, merged