Change build to esm to support plaiceholder plugin
0xsend/sendapp pull request #114
Opened 2024-02-13 08:14 UTC by youngkidwarrior

2024-02-13 08:15 UTC, youngkidwarrior commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/114?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #113** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/113?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #114** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/114?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
      * **PR #115** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/115?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/0xsend/sendapp/114?utm_source=stack-comment).

2024-02-13 16:47 UTC, 0xBigBoss reviewed
it's fine, but we need to fix CI

2024-02-17 17:28 UTC, 0xBigBoss requested changes

2024-02-17 17:28 UTC, 0xBigBoss commented on apps/next/next.config.js
>  const plugins = [
add it to the plugins list here

2024-02-18 00:08 UTC, youngkidwarrior commented on apps/next/next.config.js
>  const plugins = [
You actually wrap the returned config in a higher order function `withPlaiceholder`

https://github.com/0xsend/sendapp/pull/114/files#diff-0f913df15d01006c7733a9e4969f6335577a8a1ca3e1669c0013f57361c9ba7bR98

https://plaiceholder.co/docs/plugins/next

2024-02-18 03:10 UTC, 0xBigBoss commented on apps/next/next.config.js
>  const plugins = [
yeah it's exactly what the tamagui plugin does.

https://github.com/joe-bell/plaiceholder/blob/main/packages/next/src/index.ts

https://github.com/tamagui/tamagui/blob/master/packages/next-plugin/src/withTamagui.ts#L23

2024-02-20 02:06 UTC, 0xBigBoss commented on packages/playwright/tests/send.onboarded.spec.ts
> -  const sendDialog = page.getByRole('dialog', { name: 'Send' })
What happened to this test?

2024-02-20 02:06 UTC, 0xBigBoss commented on packages/playwright/tests/send.onboarded.spec.ts
> -  const sendDialog = page.getByRole('dialog', { name: 'Send' })
Here too?

2024-02-20 02:22 UTC, youngkidwarrior commented on packages/playwright/tests/send.onboarded.spec.ts
> -  const sendDialog = page.getByRole('dialog', { name: 'Send' })
I removed them because I thought this page didn't exist anymore

2024-02-20 03:00 UTC, youngkidwarrior commented on packages/playwright/tests/send.onboarded.spec.ts
> -  const sendDialog = page.getByRole('dialog', { name: 'Send' })
cc @0xBigBoss

2024-02-20 16:50 UTC, youngkidwarrior commented on packages/playwright/tests/send.onboarded.spec.ts
> -  const sendDialog = page.getByRole('dialog', { name: 'Send' })
think my local machine was lying to me and this wasn't the correct PR to change this. Still my changes to onboarding in future PRs will deprecate this playwright code, no?

2024-02-21 00:13 UTC, youngkidwarrior commented
@0xBigBoss SUCCESS

2024-02-21 00:26 UTC, 0xBigBoss approved these changes

2024-02-21 03:28 UTC, merged