home and account cleanup
0xsend/sendapp pull request #215
Opened 2024-03-18 22:40 UTC by 0xBigBoss

2024-03-18 23:10 UTC, youngkidwarrior commented on packages/app/components/HomeTopNav.tsx
> +}: { header: string; subheader?: string; submenuHeader?: string }) {
Do we need submenuHeader. The design just change the `header` prop 

[e.g for Personal Information]( https://www.figma.com/file/d9CZyOeYO42w4yOpeJbHES/Send-Designs-1.0?type=design&node-id=1331-1516&mode=design&t=lWlAjKjHmXlHOQ7A-4.)

2024-03-18 23:16 UTC, youngkidwarrior commented on packages/app/features/account/AccountTopNav.tsx
> +  const handleBack = () => {
Nice, I like the assert. 

side note, this is definitely hacky and I probably shouldn't have written it like this. Fine for now, but in the future should probably us the solito router + Next `URL` to do things like this

2024-03-18 23:17 UTC, youngkidwarrior commented on packages/app/features/home/layout.web.tsx
> +  TopNav,
nice

2024-03-18 23:19 UTC, youngkidwarrior commented on packages/app/features/home/screen.tsx
> +                              // fontFamily={'$mono'}
did you mean to comment these out?

2024-03-18 23:20 UTC, youngkidwarrior commented on packages/ui/src/tamagui.config.ts
> +    mono: process.env.NODE_ENV === 'test' && monoFont === undefined ? bodyFont : monoFont, // monoFont doesn't work in jest tests for some reason
Interesting. I'll look into this, but is should all be importing the same way

2024-03-18 23:22 UTC, youngkidwarrior requested changes
Looks good. Couple things and NITs 

Current colors used in settings pages make light mode unusable. Handle in future PR

2024-03-19 02:48 UTC, 0xBigBoss commented on packages/app/features/account/settings/layout.web.tsx
> +import { settingsLinks } from './SettingsBottomSheet'
Tough to say. These links won't be web specific I bet and will need to co-exist with native. Ideally we'd move it all to nav component or something.

2024-03-19 02:48 UTC, 0xBigBoss commented on packages/app/features/home/screen.tsx
> +                              // fontFamily={'$mono'}
no good eye

2024-03-19 02:49 UTC, 0xBigBoss commented on packages/ui/src/tamagui.config.ts
> +    mono: process.env.NODE_ENV === 'test' && monoFont === undefined ? bodyFont : monoFont, // monoFont doesn't work in jest tests for some reason
Don't worry about, pretty sure it's a tamagui thing. Pretty sure `@tamagui/core/native-test` is one big hack.

2024-03-19 02:50 UTC, 0xBigBoss commented on packages/app/components/HomeTopNav.tsx
> +}: { header: string; subheader?: string; submenuHeader?: string }) {
No. this shuold be dropped now.

2024-03-19 02:50 UTC, 0xBigBoss reviewed
> Looks good. Couple things and NITs 

> Current colors used in settings pages make light mode unusable. Handle in future PR 

yeah there's a lot of improvement to made here.

2024-03-19 03:15 UTC, merged