Referral Linki TopNav on Desktop
0xsend/sendapp pull request #317
Opened 2024-04-16 00:39 UTC by youngkidwarrior

2024-04-16 00:39 UTC, youngkidwarrior commented
* **#318** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/318?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#317** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/317?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @youngkidwarrior and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-16 02:49 UTC, 0xBigBoss commented on packages/app/components/ReferralLink.tsx
> +  const visualReferralUrl = `https://send.app/${primaryTag}`
this is misleading to build the link like this. I know the design has it that way (probably). 

Let's just have it link `https://send.app/` or have the text more clear `my referral link`

2024-04-16 02:50 UTC, 0xBigBoss requested changes

2024-04-16 02:50 UTC, 0xBigBoss commented on packages/app/components/ReferralLink.tsx
> +  const primaryTag = useConfirmedTags()?.at(0) ?? profile?.referral_code
also this is an object not a sendtag name.

<img width="468" alt="Screenshot 2024-04-15 at 21 49 55" src="https://github.com/0xsend/sendapp/assets/95193764/8b78f3b7-9ff5-4b92-96d2-cf5b6fd0a128">

2024-04-16 20:39 UTC, youngkidwarrior commented on packages/app/components/ReferralLink.tsx
> +  const visualReferralUrl = `https://send.app/${primaryTag}`
Sure thing, I'll just show the referral code for now

2024-04-17 02:27 UTC, 0xBigBoss commented on packages/app/components/ReferralLink.tsx
> +  const referralHref = `https://send.app/${referralCode}`
`https://send.app/${referralCode}` would make an href like this `https://send.app/myreferralcode`? It's not a valid referral code.

2024-04-17 02:28 UTC, 0xBigBoss commented on packages/app/components/TopNav.tsx
> +              // $gtLg={{ display: 'none' }}
why was this needed?

2024-04-17 02:45 UTC, youngkidwarrior commented on packages/app/components/ReferralLink.tsx
> +  const referralHref = `https://send.app/${referralCode}`
O shit. It's a query param. Designs threw me off

2024-04-17 02:45 UTC, youngkidwarrior commented on packages/app/components/TopNav.tsx
> +              // $gtLg={{ display: 'none' }}
unintenional

2024-04-18 21:07 UTC, 0xBigBoss commented on packages/app/components/ReferralLink.tsx
> +        setHasCopied(false)
this isn't working for me for some reason.

<img width="539" alt="image" src="https://github.com/0xsend/sendapp/assets/95193764/a0aba361-a230-48d2-ace6-33c6b405a7d6">

https://github.com/0xsend/sendapp/assets/95193764/ce6d825d-917e-47c2-aace-93af6d657da0

2024-04-18 21:07 UTC, 0xBigBoss approved these changes

2024-04-18 22:49 UTC, youngkidwarrior commented on packages/app/components/ReferralLink.tsx
> +        setHasCopied(false)
Haha weird. I'm going to merge for now, since not a big deal. We can fix bug in future PR

2024-04-18 22:49 UTC, youngkidwarrior commented
### Merge activity

* **Apr 18, 6:49 PM EDT**: @youngkidwarrior started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/0xsend/sendapp/317).

2024-04-18 22:50 UTC, merged