Activities mobile
0xsend/sendapp pull request #324
Opened 2024-04-17 23:51 UTC by stormcloud266

Adds mobile styles to activity page. I think this hits everything except the bottom gradient overlay. I'm working on figuring that out, but didn't want to hold up the whole PR for that.

Tablet:
![localhost_3000_activity(iPad Air)](https://github.com/0xsend/sendapp/assets/19338130/1df933bd-9ed9-436c-9638-e69f2e702432)

Phone:
![localhost_3000_activity(iPhone 12 Pro)](https://github.com/0xsend/sendapp/assets/19338130/11748f5f-3933-4fd1-af08-73d2564f867f)

2024-04-18 01:34 UTC, 0xBigBoss approved these changes
so clean. looks good. We will need them linkable in the future, but we can address that in a future PR. I forget exactly where they go to in the designs. we should clear that up with Rit.

2024-04-18 05:17 UTC, youngkidwarrior requested changes
Overall  solid work . Great pragmatic approach to separation of concerns into components. Solid responsive design. Nice tracking with TODOs

Requested a few changes in the code, but on top of those:

1. This screen shouldn't have a QR code button in `TopNav`
![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/9aagKmTbMm9lIunZ1l3e/43df0c34-1daf-4f74-bcd1-dc5556bfd369.png)

2. This is more of a NIT, but the horizontal scroll should not be Containerized. It should stretch edge to edge

<div class='graphite__hidden'>
          <div>🎥 Video uploaded on Graphite:</div>
            <a href="https://app.graphite.dev/media/video/9aagKmTbMm9lIunZ1l3e/8e681b57-a63c-4d9c-9c2e-2502b1ee7aea.mov">
              <img src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/9aagKmTbMm9lIunZ1l3e/8e681b57-a63c-4d9c-9c2e-2502b1ee7aea.mov">
            </a>
          </div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/9aagKmTbMm9lIunZ1l3e/8e681b57-a63c-4d9c-9c2e-2502b1ee7aea.mov">Screen Recording 2024-04-17 at 10.14.34 PM.mov</video>

2024-04-18 05:17 UTC, youngkidwarrior commented on packages/app/features/activity/screen.tsx
>              <IconQRCode />
The designs have a `Sort By` filter here.

[Link to Figma](https://www.figma.com/file/d9CZyOeYO42w4yOpeJbHES/Send-Designs-1.0?type=design&node-id=2649-10178&mode=design&t=Zx6J8q9QF1aonu41-4)

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/9aagKmTbMm9lIunZ1l3e/5b039959-b386-40e5-9981-35c10c93ca9c.png)

2024-04-18 05:17 UTC, youngkidwarrior commented on packages/app/features/activity/screen.tsx
>        </XStack>
<!--__GRAPHITE_HTML_TAG_START__--><i class='graphite__hidden'>[Re: line 361]<br/><br/></i>

<!--__GRAPHITE_HTML_TAG_END__-->There is a green search icon at the beginning of this Input

https://www.figma.com/file/d9CZyOeYO42w4yOpeJbHES/Send-Designs-1.0?type=design&node-id=2649-10173&mode=design&t=Zx6J8q9QF1aonu41-4<!--__GRAPHITE_HTML_TAG_START__--><span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/324?utm_source=unchanged-line-comment">Graphite</a>.</span>

<!--__GRAPHITE_HTML_TAG_END__-->

2024-04-18 14:35 UTC, stormcloud266 commented on packages/app/features/activity/screen.tsx
>              <IconQRCode />
> The designs have a `Sort By` filter here.
@youngkidwarrior I skipped the search bar entirely here since they mentioned someone else was also working on the search functionality. I definitely hit that up in this one if it isn't going to conflict with other people's work

2024-04-18 17:54 UTC, youngkidwarrior commented on packages/app/features/activity/screen.tsx
>        </XStack>
Nice I see your thinking. That seems fair

2024-04-18 22:20 UTC, stormcloud266 commented on packages/app/components/TopNav.tsx
> +          <XStack minWidth={'$4'}>{renderButton()}</XStack>
Keeps the title centered when there is no button on the right hand side of the top nav

2024-04-18 22:23 UTC, stormcloud266 commented
@youngkidwarrior started graphite tracking on this, hopefully that is easier to work with. The suggestions scroll is no longer containerized and the icon is removed from the top nav.

2024-04-19 00:03 UTC, youngkidwarrior commented
> Let me know if you want me to hit the search bar styles in this PR or I can do it in a separate one.

Nah, you're on point leaving it out of this. Good job Shax!

I'll review this ASAP

2024-04-20 00:33 UTC, youngkidwarrior approved these changes
Run `gt sync` & `gt ss` to pull latest changes

2024-04-20 19:49 UTC, merged