open modal button
0xsend/sendapp pull request #623
Opened 2024-07-24 23:40 UTC by stormcloud266

2024-07-24 23:41 UTC, stormcloud266 commented
* **#623** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/623?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @stormcloud266 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-25 06:12 UTC, youngkidwarrior commented
Honestly, you can remove the Deposited from text and the Wallet button and just use the built in (<w3m-button />)[https://docs.walletconnect.com/appkit/react/core/components] button web component from walletconnectmodal

2024-07-25 21:09 UTC, stormcloud266 commented
@youngkidwarrior updated with the web component

![Screenshot 2024-07-25 at 3 00 51 PM](https://github.com/user-attachments/assets/1a4e8e57-ef73-4e3a-b3d7-44607e584347)

2024-07-26 10:02 UTC, youngkidwarrior requested changes
looks good but lets cleanup this page a little, since we are already here

2024-07-26 10:02 UTC, youngkidwarrior commented on packages/app/features/deposit/web3/screen.tsx
>    const { address: account } = useAccount()
This flow is a little wonky. Remove the `useEffect` call. Just have people choose between clicking the Connect Button or directly depositing.

 `<w3m-button/>` should be able to cover all these cases. You might have to specify the preferred chain id. 

Also can you make sure the `<DepositAddress/>` component is visible before the wallet is connected. At the moment it only shows after connected

2024-07-26 20:45 UTC, stormcloud266 commented on packages/app/features/deposit/web3/screen.tsx
>    const { address: account } = useAccount()
Not sure if i can pass a preferred chain id to the <w3m-button/> component, but it does force me to switch back to base if i change chains. 

I got those other two requests in as well. It shows when not connected as well

![Screenshot 2024-07-26 at 2 30 37 PM](https://github.com/user-attachments/assets/913b8818-e226-489d-b799-a2c81bd8ce60)

2024-07-26 21:10 UTC, youngkidwarrior commented on packages/app/features/deposit/web3/screen.tsx
>    const { address: account } = useAccount()
Yeah you're almost there. The `Connect to Deposit` Button can just be replaced by <w3m-button>. It will handle the `isConnected` state and stuff itself

2024-07-26 21:11 UTC, youngkidwarrior commented on packages/app/features/deposit/web3/screen.tsx
>    const { address: account } = useAccount()
Also button looks kinda funky in light mode 
![Uploading Screenshot 2024-07-26 at 2.07.09 PM.png…]()

2024-07-27 05:51 UTC, youngkidwarrior approved these changes

2024-08-02 20:52 UTC, merged