remove sign-in page
0xsend/sendapp pull request #681
Opened 2024-08-24 00:19 UTC by stormcloud266

2024-08-24 00:19 UTC, stormcloud266 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/681?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#681** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/681?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#679** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/679?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @stormcloud266 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-25 01:00 UTC, youngkidwarrior requested changes

2024-08-25 01:00 UTC, youngkidwarrior commented on packages/app/features/unknown/screen.tsx
> +        <Link href="/">
Wrapping Button in Link is actually an anti-pattern. Let's take this opportunity to fix this and use the `<LinkableButton/>` component

side note, do you like the name `LinkableButton?` Any better suggestions?

2024-08-25 21:19 UTC, youngkidwarrior commented
Let's stack a PR on top of this and deal with these errors 

![image](https://github.com/user-attachments/assets/b85297ef-9b66-47c8-a61f-816b202c03b5)

2024-08-27 00:27 UTC, youngkidwarrior requested changes

2024-08-27 00:27 UTC, youngkidwarrior commented on packages/app/features/splash/screen.tsx
> +      >
Not quite. Instead of passing the props let's just switch between two buttons
```suggestion
     isSigningIn ? 
     <SignInButton 
        size="$4"
        w="$12"
        disabled
        disabledStyle={..}>
      <SignInButton.Text>
        Signing In...
      </SignInButton.Text>
     </SignInButton> :
     <SignInButton
        size="$4"
        w="$12"
        onPress={handleSignIn}
      >...
```

2024-08-27 00:29 UTC, youngkidwarrior requested changes
Same as change below. No need to have the sign in logic in the actual button

2024-08-27 00:30 UTC, youngkidwarrior requested changes
Same as below

2024-08-27 00:31 UTC, youngkidwarrior reviewed
Looking good. One small change and we are golden

2024-08-27 00:40 UTC, stormcloud266 commented on packages/app/features/splash/screen.tsx
> +      >
Not sure I get what you're saying here. The SignInButton is already responsible for all the sign in logic, the only thing that needs changing between it's two current uses is the text and button text styles

2024-08-27 01:06 UTC, youngkidwarrior commented on packages/app/features/splash/screen.tsx
> +      >
The logic for signing in, like the mutation and and query param handlers shouldn’t be in the button. The button should just be styles and html. Let the parent component control all the logic.

2024-08-27 02:20 UTC, stormcloud266 commented on packages/app/features/splash/screen.tsx
> +      >
The button is currently used in multiple spots, so I can move the logic to a hook or whatever, but moving it to the parent means duplicating all that code in both spots

2024-08-28 02:38 UTC, youngkidwarrior commented on packages/app/features/splash/screen.tsx
> +      >
It's okay to repeat code a little in this case. Buttons shouldn't be managing all that state. If you'd like to move the sign in logic into a hook as well, I think that's a smart idea. If we find ourselves rewriting the sign in stuff a lot we can always add the hook later

2024-08-28 22:43 UTC, stormcloud266 commented on packages/app/features/splash/screen.tsx
> +      >
Okay i'll copy pasta and then we can do a hook later if we need to

2024-08-29 01:09 UTC, youngkidwarrior approved these changes

2024-08-30 00:06 UTC, youngkidwarrior commented
### Merge activity

* **Aug 29, 8:06 PM EDT**: @youngkidwarrior started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/0xsend/sendapp/681).

2024-08-30 00:08 UTC, merged