- Added theme colors, sizes and updated palletes
0xsend/sendapp pull request #7
Opened 2023-12-05 13:49 UTC by syedehsans1

- Implemented Dashboard(Home) Screen

2023-12-05 14:53 UTC, 0xLe0x reviewed
added some comments, thanks @syedehsans1

2023-12-05 14:53 UTC, 0xLe0x commented on apps/next/public/close.png
should use SVG instead of PNG for light/dark mode.
Plz take a look at  `packages/app/components/icons`

2023-12-05 14:53 UTC, 0xLe0x commented on apps/next/public/close_dark.png
This one as well

2023-12-05 14:53 UTC, 0xLe0x commented on apps/next/public/close.png
I already added this icon and will be pushing it soon. You can use them in your code.

2023-12-05 14:53 UTC, 0xLe0x commented on packages/app/components/layout/footer/index.tsx
> +    <Footer pos={'absolute'} b={0} px={36} width="100%" height={'$10'} >
is this a problem with your prettier?

2023-12-05 16:42 UTC, 0xBigBoss requested changes
thx @syedehsans1. lookin pretty good. Could you drop me a link to how we are going to use the brand theme? would it be like `theme="send"`?


let's also convert the pngs to svg as @0xLe0x said.

2023-12-05 16:42 UTC, 0xBigBoss commented on packages/app/features/home/screen.tsx
> +                  {/* @ts-ignore */}
please use `@ts-expect-error <reason>`

2023-12-05 16:42 UTC, 0xBigBoss commented on packages/app/features/home/screen.tsx
> +                  {/* @ts-ignore */}
ditto

2023-12-05 16:42 UTC, 0xBigBoss commented on packages/ui/src/themes/token-colors.ts
> +  sendDark
export a `sendLight` instead, even if it's just a copy of `sendDark`

```tsx
export const sendLight = {
  ...sendDark
}
```

That way it's easier to add once we have the light colors nailed down.

2023-12-05 16:42 UTC, 0xBigBoss commented on packages/ui/src/themes/token-size.ts
> +  '$s16': 16,
typo?

2023-12-05 16:42 UTC, 0xBigBoss commented on packages/app/features/home/screen.tsx
> +  const CommentsTime = (dateString: any) => {
move to a utils file and add a vitest for it please.

also why `any`? should just be string right?

2023-12-28 15:52 UTC, syedehsans1 commented on packages/ui/src/themes/token-size.ts
> +  '$s16': 16,
its intentional

2023-12-28 20:56 UTC, 0xBigBoss requested changes
few more things before the home screen is mergable.

I think we should probably simplify the theme updates until we can understand it's API better and not try to do too much with our PRs. Please separate out the theme changes into another PR.

I also received access to Tamagui studio so once I'm done with onboarding I can help install a proper theme.

2023-12-28 20:56 UTC, 0xBigBoss commented on apps/next/public/avatar.png
delete for now, just use a placeholder or make the box a color

2023-12-28 20:56 UTC, 0xBigBoss commented on packages/app/features/auth/sign-in-screen.tsx
somethings off with the light theme
<img width="428" alt="Screenshot 2023-12-28 at 14 40 17" src="https://github.com/0xsend/sendapp/assets/95193764/4c30f32d-3ff5-492d-8c59-ce36450e61cd">

2023-12-28 20:56 UTC, 0xBigBoss commented on packages/app/features/home/screen.tsx
> +import { MainLayout } from '../../components/layout';
us the tsconfig paths setting.

```suggestion
import { MainLayout } from 'app/components/layout';
```

2023-12-28 20:56 UTC, 0xBigBoss commented on packages/app/features/home/screen.tsx
> +                              <Avatar.Image src={transaction.type == 'inbound' ? './recieveIcon.png' : './sendButtonIcon.png'}></Avatar.Image>
getting a bunch of 404s. plus should these be svgs?

<img width="510" alt="Screenshot 2023-12-28 at 14 42 27" src="https://github.com/0xsend/sendapp/assets/95193764/cac1d023-ca54-437b-90bb-ac4fce07d6b6">

2023-12-28 20:56 UTC, 0xBigBoss commented on packages/app/provider/theme/UniversalThemeProvider.native.tsx
> +type ThemeName = 'light' | 'dark' | 'system' | 'send'
I don't think this is the right approach. We don't want send to be a top-level theme.

2023-12-28 20:56 UTC, 0xBigBoss commented on packages/app/utils/dateHelper.ts
add a dateHelper.test.ts please.

2023-12-28 20:56 UTC, 0xBigBoss commented on packages/ui/src/components/FormFields/TextField.tsx
> +            theme={themeName.startsWith("dark") ? "light" : "gold"}
what's this for? this would override the red theme component that it's wrapped in.

2023-12-28 20:56 UTC, 0xBigBoss commented on packages/ui/src/themes/colors.ts
> +  '#000',
why is this flipped?

2023-12-28 20:56 UTC, 0xBigBoss commented on packages/ui/src/themes/templates.tsx
can you share with everyone on what this is doing?

2023-12-28 20:56 UTC, 0xBigBoss commented on packages/wagmi/src/generated.ts
revert this file

2023-12-28 20:56 UTC, 0xBigBoss commented on packages/ui/src/themes/token-size.ts
> +  '$s16': 16,
hmm, not sure exactly what the size props translate to, but feel like we should follow the convention already setup. what about renaming it to something like `$0.9`?

2023-12-28 20:56 UTC, 0xBigBoss commented on apps/next/public/balanceCard.png
also delete for now, we will figure out the best way to include stuff like this later.

2024-01-03 02:16 UTC, 0xBigBoss reviewed
seems like a few things from my last review are still open, plus a few more things i noticed on this.

2024-01-03 02:16 UTC, 0xBigBoss commented on packages/app/components/icons/IconEthereum.tsx
> +      <g clip-path="url(#clip0_563_1431)">
this doesn't look transformed correctly for react native.

2024-01-03 02:16 UTC, 0xBigBoss commented on packages/app/components/icons/IconArrowDown.tsx
> +				<linearGradient id="paint0_linear_563_1349" x1="20" y1="-59.5" x2="15" y2="54.5" gradientUnits="userSpaceOnUse">
same here, seems off, why no import for linearGradient?

2024-01-03 02:16 UTC, 0xBigBoss commented on packages/app/components/icons/IconSend.tsx
> +				<clipPath id="clip0_563_1426">
ditto

2024-01-03 02:16 UTC, 0xBigBoss commented on packages/wagmi/src/generated.ts
revert please

2024-01-03 15:11 UTC, syedehsans1 commented
> thx @syedehsans1. lookin pretty good. Could you drop me a link to how we are going to use the brand theme? would it be like `theme="send"`?
> 
> let's also convert the pngs to svg as @0xLe0x said.

yup, theme="send" would work

2024-01-03 16:03 UTC, 0xBigBoss reviewed
Theme is looking really great now. Just a few more questions, I think after this round it's ready to go.

2024-01-03 16:03 UTC, 0xBigBoss commented on packages/ui/src/themes/palettes.tsx
> +  const lightTransparent = 'rgba(22, 22, 25, 0)'
why are these flipped? can you screenshot some examples why this is needed?

2024-01-03 16:03 UTC, 0xBigBoss commented on packages/ui/src/themes/palettes.tsx
> +    '#000',
same here. why are these flipped? can you screenshot some examples why this is needed?

2024-01-03 16:03 UTC, 0xBigBoss commented on packages/ui/src/themes/templates.tsx
> +    // Integer value represent the index of color in 12 color palette. The platte values can be located in token-colors.ts file
ty. makes sense.

2024-01-04 14:55 UTC, syedehsans1 commented on packages/ui/src/themes/palettes.tsx
> +    '#000',
it was a mistake, reverted in colors.tsx forgot to do it here

2024-01-09 16:04 UTC, 0xBigBoss approved these changes
looks good, could you please format and lint the code with biome before merging?

If you merge the latest main, you can use the latest version of biome to format and lint your changed files.

```shell
yarn
npx biome check --apply --changed --files-ignore-unknown=true
```
Also update the home.screen snapshot. There's a button on the app:test resource.

<img width="1467" alt="Screenshot 2024-01-09 at 10 04 00" src="https://github.com/0xsend/sendapp/assets/95193764/b0f07ac2-7490-4276-9cd4-caa86131473f">

or run `yarn test -u` in the app package.

2024-01-11 18:54 UTC, 0xBigBoss commented on supabase/database-generated.types.ts
I'd revert this file and not include it in the changes @syedehsans1

2024-01-15 15:43 UTC, merged