account page styles
0xsend/sendapp pull request #711
Opened 2024-09-11 23:03 UTC by stormcloud266

2024-09-11 23:03 UTC, stormcloud266 commented
* **#711** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/711?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @stormcloud266 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-11 23:24 UTC, youngkidwarrior requested changes
Light theme looks off. You'll have to manually set all the green to black, since the color themes don't support this yet.

`$theme-light:{{col: "$color12"}}`

Everything else looks good

![Screenshot 2024-09-11 at 4.18.21 PM.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/9aagKmTbMm9lIunZ1l3e/d3adfd27-c0ed-42d4-83c9-6588e295ce31.png)

2024-09-12 23:50 UTC, stormcloud266 commented
@youngkidwarrior tried olive on the icons, let me know what you think. also fixed that stretch issue on tall screens

<img width="1094" alt="Screenshot 2024-09-12 at 5 49 09 PM" src="https://github.com/user-attachments/assets/bc322a1e-7a86-4b76-96d9-61501a6f8c33">

2024-09-13 00:06 UTC, youngkidwarrior requested changes
Couple comments about colors. Let me know if you want to do a quick meaning to run through how radix colors work

2024-09-13 00:06 UTC, youngkidwarrior commented on packages/app/features/account/screen.tsx
> +          <Button.Icon>{icon}</Button.Icon>
```suggestion
          <Button.Icon theme="green_active" $theme-light={{col:"$color12"}}>{icon}</Button.Icon>
```

2024-09-13 20:27 UTC, stormcloud266 commented on packages/app/features/account/screen.tsx
> +      icon: <IconBadgeCheck size={22} color={'$primary'} $theme-light={{ color: '$olive' }} />,
sounds good will push those changes shortly

2024-09-13 20:30 UTC, stormcloud266 commented on packages/app/features/account/screen.tsx
> +          <Button.Icon>{icon}</Button.Icon>
Had to go with the Theme parent like you previous example

2024-09-13 20:31 UTC, stormcloud266 commented on packages/app/features/account/screen.tsx
> +      icon: <IconBadgeCheck size={22} color={'$primary'} $theme-light={{ color: '$olive' }} />,
okay they are all updated. noticed the avatar fallback was always olive and updated it to match the one in the nav

<img width="803" alt="Screenshot 2024-09-13 at 2 26 43 PM" src="https://github.com/user-attachments/assets/406fe4f5-7fff-419f-bf73-20c841cf9e1c">

2024-09-14 06:43 UTC, youngkidwarrior approved these changes

2024-09-14 06:43 UTC, youngkidwarrior commented
### Merge activity

* **Sep 14, 2:43 AM EDT**: @youngkidwarrior started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/0xsend/sendapp/711).

2024-09-14 06:44 UTC, merged