Handle already used phone in UI
0xsend/sendapp pull request #866
Opened 2024-11-15 09:51 UTC by musidlo

2024-11-15 17:14 UTC, youngkidwarrior approved these changes
Changes look good, a couple touchups here and there.

I would have preferred you split moving the functions and modifying the components into separate PRs so it's easier to pick out the logic from the refactors

2024-11-15 17:14 UTC, youngkidwarrior commented on packages/api/src/routers/_app.ts
> +import { authRouter } from './auth/router'
Is there a specific reason to change this route?

2024-11-15 17:14 UTC, youngkidwarrior commented on packages/app/features/auth/sign-up/sign-up-form.tsx
> +  const handleSignIn = async (isNumberAlreadyUsed = false) => {
NIT: maybe should be `isPhoneAlreadyUsed` to maintain consistency

2024-11-15 17:14 UTC, youngkidwarrior commented on packages/app/features/auth/sign-up/sign-up-form.tsx
> +              <SubmitButton onPress={() => handleSignIn()} disabled={isSigningIn} unstyled>
dont have to make this an arrow function since it has no args

`onPress={handleSignIn}`

is there a reason for the change

2024-11-15 17:14 UTC, youngkidwarrior commented on packages/app/features/auth/sign-up/sign-up-form.tsx
> +          borderColor="$primary"
for light mode primary is always assigned to black. Unfortunately our tamagui doesn't do this for us yet


```suggestion
          borderColor="$primary"
          $theme-light={{borderColor: "$color12"}}
```

2024-11-15 17:17 UTC, youngkidwarrior commented on packages/app/features/auth/sign-up/sign-up-form.tsx
> +    void signUpWithPhone(formData, true)
NIT: This boolean is a bit magical. Hard to know what it does. Consider using a string enum or passing it in a object so we can name it

2024-11-15 17:17 UTC, youngkidwarrior commented on packages/app/features/auth/sign-up/sign-up-form.tsx
> +        await handleSignIn(true)
See NIT below

2024-11-15 17:50 UTC, youngkidwarrior commented on packages/app/features/auth/sign-up/sign-up-form.tsx
> +          <Button.Text color="$white" $gtMd={{ color: '$color12' }}>
This won't work on light mode. Instead use our radix-style color pallette


```suggestion
          <Button.Text color="$color12">
```

2024-11-15 17:54 UTC, youngkidwarrior requested changes
Found a bug

2024-11-15 17:54 UTC, youngkidwarrior commented on packages/app/features/auth/sign-up/sign-up-form.tsx
>      setIsSigningIn(true)
There is some logical flaw in sign in. If I put the wrong passkey, it pushes me to the Verify Code screen with a phone that exists already

![IMG_4202.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/9aagKmTbMm9lIunZ1l3e/c29cd55a-fdc2-4ebf-87c1-76b6f6599f93.png)

2024-11-15 18:01 UTC, musidlo commented on packages/app/features/auth/sign-up/sign-up-form.tsx
>      setIsSigningIn(true)
on it

2024-11-15 18:02 UTC, musidlo commented on packages/app/features/auth/sign-up/sign-up-form.tsx
> +              <SubmitButton onPress={() => handleSignIn()} disabled={isSigningIn} unstyled>
actually there is a reason I did that, on press is passing event as a arg to the function, and this function have optional arg, typescript complains about types mismatch between event and function param, and it's right

2024-11-16 02:27 UTC, youngkidwarrior commented on packages/app/features/auth/sign-up/sign-up-form.tsx
> +              <SubmitButton onPress={() => handleSignIn()} disabled={isSigningIn} unstyled>
Ah ok I see. Looks good

2024-11-18 21:06 UTC, youngkidwarrior approved these changes

2024-11-18 21:11 UTC, merged