Add X username to personal data
0xsend/sendapp pull request #882
Opened 2024-11-22 17:18 UTC by musidlo

2024-11-22 19:23 UTC, 0xBigBoss commented on packages/app/components/FormFields/TextField.tsx
> +            {label} {isOptional && !props.hideOptionalLabel && '(Optional)'}
I'd rather just remove the optional bit altogether, don't like this boolean style props that control components children rendering logic.

I don't think we have `(Optional)` anywhere in our designs anyway.

2024-11-22 21:56 UTC, youngkidwarrior commented on packages/app/features/account/settings/personal-info.tsx
> +  async function handleSubmit() {
I'd probably use two different forms, instead of grouping logic into one handleSubmit. It's more verbose but easier to grock

2024-11-22 21:56 UTC, youngkidwarrior commented on packages/app/utils/useAuthUserMutation.ts
> +  xUsername: formFields.text.optional().describe('X'),
Should probably be different forms since changing X doesn't require phone confirm

2024-11-22 21:56 UTC, youngkidwarrior commented on packages/app/utils/useUserPersonalDataMutation.ts
> +    async mutationFn(data: z.infer<typeof AuthUserSchema>) {
Will need a different schema if we separate the forms

2024-11-22 22:13 UTC, musidlo commented on packages/app/features/account/settings/personal-info.tsx
> +  async function handleSubmit() {
How do you imagine separating the forms from UI perspective? On the designs it's one form with submit button

2024-11-22 22:16 UTC, youngkidwarrior commented on packages/app/features/account/settings/personal-info.tsx
> +  async function handleSubmit() {
yeah thats an oversight of design. I guess we leave it like this and bring it up in the future

2024-11-22 22:19 UTC, musidlo commented on packages/app/features/account/settings/personal-info.tsx
> +  async function handleSubmit() {
from UX perspective I not if I would like to have two forms, one for phone only and the other for the rest, not sure there. this data won't be changed often, especially phone number

2024-11-22 22:51 UTC, youngkidwarrior approved these changes

2024-11-22 22:59 UTC, youngkidwarrior requested changes
Make sure you pull the latest changes from dev. I think you are missing migrations

2024-11-22 23:18 UTC, musidlo commented
> Make sure you pull the latest changes from dev. I think you are missing migrations

done

2024-11-23 00:02 UTC, youngkidwarrior approved these changes

2024-11-25 08:58 UTC, merged