Add x username to profile lookup
0xsend/sendapp pull request #898
Opened 2024-11-25 09:24 UTC by musidlo

2024-11-25 15:38 UTC, musidlo commented on supabase/migrations/20241125111812_add-x-username-to-profile-lookup.sql
> + IMMUTABLE SECURITY DEFINER
didnt change that, thats how this function was defined

2024-11-26 16:15 UTC, youngkidwarrior requested changes
This looks good on first glance but I'm gonna come back to it a second time when I'm not so busy. 

If @0xBigBoss has time for review then we can merge

This is a staple function in the codebase and I need more time to read it and learn it

2024-11-26 17:26 UTC, musidlo commented
> This looks good on first glance but I'm gonna come back to it a second time when I'm not so busy.
> 
> If @0xBigBoss has time for review then we can merge
> 
> This is a staple function in the codebase and I need more time to read it and learn it

use compare with current implementation, small changes
![image](https://github.com/user-attachments/assets/a87a3e71-9b3b-43ab-894c-98eeb6e03267)

2024-11-27 08:40 UTC, youngkidwarrior commented
We aren't checking if the X username is unique and accurate. Why add this to profile_lookup?

2024-12-03 11:28 UTC, youngkidwarrior commented
Please make sure to reorder this migration before merging it!

2024-12-03 11:28 UTC, youngkidwarrior approved these changes

2024-12-03 16:29 UTC, merged