Add birthday to personal info
0xsend/sendapp pull request #917
Opened 2024-12-03 17:01 UTC by musidlo

2024-12-04 08:24 UTC, youngkidwarrior requested changes

2024-12-04 08:24 UTC, youngkidwarrior commented on packages/app/utils/dateHelper.ts
> +
Seems like we may have some timezone issues with displaying the date


Uploading Screen Recording 2024-12-04 at 12.21.53 AM.mov…

2024-12-04 16:36 UTC, musidlo commented on packages/app/utils/dateHelper.ts
> +
@youngkidwarriorI think uploading a screen recording went wrong?

2024-12-04 17:53 UTC, youngkidwarrior commented on packages/app/utils/dateHelper.ts
> +
Damn it did. It shows September 5 when I click September 6. 

Probably showing UTC time

2024-12-04 18:18 UTC, musidlo commented on packages/app/utils/dateHelper.ts
> +
alright, I will work on this to fix it, but first I would like to finish previous PRs, this is last in the queue

2024-12-04 18:36 UTC, youngkidwarrior commented on packages/app/utils/dateHelper.ts
> +
Still gotta read through those. Just easy to try this one out

2024-12-12 00:40 UTC, youngkidwarrior commented on packages/app/utils/dateHelper.ts
> +export const formatDateToSupabaseFormat = (date: Date): string => {
Can remove this function. Supabase accepts ISO format.

2024-12-12 00:41 UTC, youngkidwarrior commented on packages/app/utils/useUserPersonalDataMutation.ts
> +      const birthdayToUpdate = data.birthday ? formatDateToSupabaseFormat(data.birthday) : null
```suggestion
      const birthdayToUpdate = data.birthday ?data.birthday.toISOString() : null
```

2024-12-12 00:44 UTC, youngkidwarrior commented on packages/app/utils/dateHelper.ts
> +export const parseSupabaseDateStringToDate = (dateString: string): Date => {
You don’t need this helper either

2024-12-12 00:51 UTC, youngkidwarrior commented on packages/app/features/account/settings/personal-info.tsx
> +    const birthday = profile?.birthday ? parseSupabaseDateStringToDate(profile.birthday) : undefined
I believe the month problem was that our db dates our UTC. 
```suggestion
    const birthday = profile?.birthday ? 
adjustUTCDateForTimezone(new Date(profile.birthday)) : undefined
    

```

2024-12-12 00:51 UTC, youngkidwarrior commented on packages/app/features/account/settings/personal-info.tsx
> +    const birthday = profile?.birthday ? parseSupabaseDateStringToDate(profile.birthday) : undefined
See below

2024-12-12 00:53 UTC, youngkidwarrior requested changes
Could probably just use built in JS functions

2024-12-12 15:50 UTC, musidlo commented on packages/app/utils/dateHelper.ts
> +export const formatDateToSupabaseFormat = (date: Date): string => {
Disagree here
Supabase accespts ISO format but it is not the same as what I implemented here
lets say you have following date object: `Fri Dec 06 2024 00:00:00 GMT+0100 `
this function formatDateToSupabaseFormat will return following string: `2024-12-06`
toISOString will return following string: `2024-12-05T23:00:00.000Z`
using it might be buggy, due to suppabase is saving only date
![image](https://github.com/user-attachments/assets/e30dc601-1aeb-40ab-aa0f-d4583dfeb2de)

2024-12-12 15:51 UTC, musidlo commented on packages/app/utils/useUserPersonalDataMutation.ts
> +      const birthdayToUpdate = data.birthday ? formatDateToSupabaseFormat(data.birthday) : null
explained here https://github.com/0xsend/sendapp/pull/917#discussion_r1882415718

2024-12-12 15:59 UTC, musidlo commented on packages/app/features/account/settings/personal-info.tsx
> +    const birthday = profile?.birthday ? parseSupabaseDateStringToDate(profile.birthday) : undefined
results are the same, applied

2024-12-12 17:19 UTC, youngkidwarrior commented on packages/app/utils/dateHelper.ts
> +export const formatDateToSupabaseFormat = (date: Date): string => {
Let's keep all the dates in the database in UTC. This saves them in their local time zone correct?

2024-12-14 17:03 UTC, youngkidwarrior commented on packages/app/utils/dateHelper.ts
> +export const adjustMidnightToTimezone = (date: Date): Date => {
Nit: Kinda a funny name. Doesn't really tell me what it does. Would be better to denote this is used for supabase Date type

2024-12-14 17:07 UTC, youngkidwarrior commented on packages/app/utils/dateHelper.ts
>  export const formatDateToLongForm = (date?: Date): string => {
Nit: these two functions are a bit overkill no?

why not all in one and get rid of the helpers?
`date.toLocaleString('en-US', {day:numeric, month: 'long', year:numeric })`

2024-12-14 17:16 UTC, youngkidwarrior requested changes
Functionality looks good. Couple Nits

Light mode styling is wonky. 

![Screenshot 2024-12-14 at 9.14.24 AM.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/9aagKmTbMm9lIunZ1l3e/a5b27134-13ee-437e-bc58-5a08d8f5b9ed.png)

2024-12-16 16:25 UTC, musidlo commented on packages/app/utils/dateHelper.ts
>  export const formatDateToLongForm = (date?: Date): string => {
because it is different on the designs, wanted to do it exacly how it is designed
also we dont want to show year here, designs show only day and month

2024-12-16 16:26 UTC, musidlo commented on packages/app/utils/dateHelper.ts
> +export const adjustMidnightToTimezone = (date: Date): Date => {
it's date picker date type, I changed the name

2024-12-16 17:08 UTC, musidlo commented
> Functionality looks good. Couple Nits
> 
> Light mode styling is wonky.

Hey @youngkidwarrior fixed styling for light theme

2024-12-17 05:54 UTC, youngkidwarrior commented on packages/app/utils/dateHelper.ts
>  export const formatDateToLongForm = (date?: Date): string => {
That's fine, just giving an example. Why write helper functions when we have a one liner that's descriptive?

2024-12-17 07:25 UTC, musidlo commented on packages/app/utils/dateHelper.ts
>  export const formatDateToLongForm = (date?: Date): string => {
this is what you gonna get 
![image](https://github.com/user-attachments/assets/620f8a2e-de3c-4bdf-ae1c-19a031487e88)

and this is what you want to get
![image](https://github.com/user-attachments/assets/fe926ca4-c5b0-43fa-b5f7-26a8ac7752e2)

2024-12-17 07:34 UTC, musidlo commented on packages/app/utils/dateHelper.ts
>  export const formatDateToLongForm = (date?: Date): string => {
let me know

2024-12-17 07:49 UTC, youngkidwarrior commented on packages/app/utils/dateHelper.ts
>  export const formatDateToLongForm = (date?: Date): string => {
ah I see. F that design ahahaha. just use locale string

2024-12-17 16:18 UTC, musidlo commented on packages/app/utils/dateHelper.ts
>  export const formatDateToLongForm = (date?: Date): string => {
applied

2024-12-17 18:43 UTC, youngkidwarrior approved these changes

2024-12-17 18:44 UTC, youngkidwarrior commented
### Merge activity

* **Dec 17, 1:44 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/0xsend/sendapp/917).

2024-12-17 18:44 UTC, merged