Redesigned mobile nav
0xsend/sendapp pull request #946
Opened 2024-12-12 22:15 UTC by musidlo

2024-12-14 17:42 UTC, youngkidwarrior commented on packages/app/components/NavSheet.tsx
> +          <Paragraph size={'$10'}>/send</Paragraph>
This doesn't match the logo styling in the rest of the app.

Let's use the svg instead
```suggestion
       <Link href="/send">
                      <IconSendLogo size={'$2.5'} color={'$color12'} />
                    </Link>
```

2024-12-14 17:42 UTC, youngkidwarrior requested changes
One change

Using `first` and `last` works for now, but look into [Tamagui UI Groups](https://tamagui.dev/ui/group) \

2024-12-16 16:12 UTC, musidlo commented
> One change
> 
> Using `first` and `last` works for now, but look into [Tamagui UI Groups](https://tamagui.dev/ui/group) \

@youngkidwarrior those links are put placed in scroll view. If I put there a group it doesnt make sense to keep in in scroll view imo. It's either scroll view with individual items or buttons group. originally it was scroll view so I wanted to keep it this way. let me know what you think

2024-12-16 16:22 UTC, musidlo commented on packages/app/components/sidebar/SideBarNavLink.tsx
> +        href={props.disabled ? '' : props.href}
that's how I wanted it to be

2024-12-17 05:39 UTC, youngkidwarrior commented
leave it for now. Better to reduce complexity. Leave it a lil smelly lol

2024-12-17 05:40 UTC, youngkidwarrior approved these changes

2024-12-17 05:40 UTC, youngkidwarrior commented
### Merge activity

* **Dec 17, 12:40 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/0xsend/sendapp/946).

2024-12-17 05:40 UTC, merged