Redesign send search
0xsend/sendapp pull request #960
Opened 2024-12-17 22:03 UTC by musidlo

2024-12-17 22:09 UTC, musidlo commented on packages/app/components/SearchBar.tsx
> +                  </Stack>
alright, you are the boss here, changed it to be a button

2024-12-18 20:43 UTC, youngkidwarrior commented
![image](https://github.com/user-attachments/assets/84e8b9b3-d51d-44da-9816-00b75b386c59)

Light mode is a little hard to read. Let's darken the placeholder text

2024-12-18 22:25 UTC, musidlo commented
Hey @youngkidwarrior, darkened placeholder color on light mode, also as Ethen asked, I removed italics from placeholder, bumped font size of it and modified search icon

2024-12-19 07:43 UTC, youngkidwarrior requested changes

2024-12-19 07:43 UTC, youngkidwarrior commented on packages/app/features/send/components/SendTopNav.tsx
> +                  return 'Send'
One more thing.

 hide the Send header on desktop. Align the search bar with top of other screens

2024-12-19 09:13 UTC, youngkidwarrior approved these changes

2024-12-19 10:56 UTC, merged