Redesign send amount
0xsend/sendapp pull request #963
Opened 2024-12-20 22:23 UTC by musidlo

2024-12-20 22:23 UTC, musidlo commented on packages/app/features/profile/components/ProfileAboutTile.tsx
moved to separated file

2024-12-20 22:23 UTC, musidlo commented on packages/app/features/profile/components/ProfileHeader.tsx
moved to separated file

2024-12-20 22:24 UTC, musidlo commented on packages/app/features/profile/screen.tsx
> +                  <ProfileHeader
moved to separated file

2024-12-20 22:24 UTC, musidlo commented on packages/app/features/profile/screen.tsx
> -
moved to separated file

2024-12-21 13:29 UTC, musidlo commented on packages/app/features/profile/components/ProfileAboutTile.tsx
> +                `https://ui-avatars.com/api.jpg?name=${otherUserProfile?.name ?? '??'}&size=256`
Guess name is checked when setting

2024-12-21 19:08 UTC, youngkidwarrior commented on packages/app/features/send/SendAmountForm.tsx
> +  const [isProfileInfoVisible, setIsProfileInfoVisible] = useState<boolean>(false)
Now that we use this in two screens, let’s hoist the state into the url

That way we can navigate between pages using the web router

 add it to `RootScreenParams` in `/params/`

Then use the `useRootScreenParams` hook


You will have to update it in send amount and profile screen

2024-12-21 19:10 UTC, youngkidwarrior approved these changes
This is looking good 

Time to use url params for our modals. Feel free to stack that PR on top of this one

2024-12-23 02:32 UTC, youngkidwarrior requested changes

2024-12-23 02:32 UTC, youngkidwarrior commented on packages/app/features/profile/components/ProfileHeader.tsx
> +        <AvatarProfile profile={profile} mx="none" size="$6" />
Let's replace this with a `<LinkableAvatar/>` component so we can Link to the profile if they click the profile image

2024-12-23 06:13 UTC, musidlo commented on packages/app/features/profile/components/ProfileHeader.tsx
> +        <AvatarProfile profile={profile} mx="none" size="$6" />
I added it to my todo list, lets move on, want to finish redesign before my christmas break

2024-12-23 09:09 UTC, youngkidwarrior commented on packages/app/features/profile/components/ProfileHeader.tsx
> +        <AvatarProfile profile={profile} mx="none" size="$6" />
Nah, this should ship with this PR because it would be a regression

Many rely on this functionality to quickly check their previous sends to the account

[here is the old image component](https://github.com/0xsend/sendapp/blob/dev/packages/app/features/send/confirm/screen.tsx#L414-L419)

2024-12-23 09:13 UTC, youngkidwarrior commented on packages/app/features/profile/components/ProfileHeader.tsx
> +        <AvatarProfile profile={profile} mx="none" size="$6" />
Don’t worry if you don’t finish. I will get it over the line

2024-12-23 13:08 UTC, musidlo commented on packages/app/features/profile/components/ProfileHeader.tsx
> +        <AvatarProfile profile={profile} mx="none" size="$6" />
applied

2024-12-23 13:45 UTC, youngkidwarrior requested changes
caught a couple more things. Can't let it get to prod yet

2024-12-23 13:45 UTC, youngkidwarrior commented on packages/app/features/profile/components/ProfileHeader.tsx
> +        <LinkableAvatar size="$6" br="$4" href={href}>
Funny behavior when clicking PFP. getting both actions. Need to stop propogation
something like this
```onPressOut={(e) => e.stopPropagation()}```

https://github.com/user-attachments/assets/8e1f953e-bd63-4fca-bc82-0dc38d05f0c6

2024-12-23 13:45 UTC, youngkidwarrior commented on packages/app/features/send/SendAmountForm.tsx
> +                      form.setValue('amount', localizeAmount(formatUnits(balance, decimals)))
This max button is going to cause problems for USDC. If a user tries to send all their USDC, then the operation will fail.

Right now our gas estimates suck ass, so in order not to confuse anybody, let's just remove "Max" Button when USDC is selected

2024-12-23 13:45 UTC, youngkidwarrior commented on packages/app/features/send/SendAmountForm.tsx
> +                <Button.Text fontWeight={'600'}>SEND</Button.Text>
This should say CONTINUE. Don't worry about designs

2024-12-23 14:39 UTC, musidlo commented on packages/app/features/send/SendAmountForm.tsx
> +                <Button.Text fontWeight={'600'}>SEND</Button.Text>
applied

2024-12-23 14:39 UTC, musidlo commented on packages/app/features/send/SendAmountForm.tsx
> +                      form.setValue('amount', localizeAmount(formatUnits(balance, decimals)))
applied

2024-12-23 19:11 UTC, youngkidwarrior commented
Let’s keep these buttons looking the same and same height between recipient and confirm pages


https://github.com/user-attachments/assets/068bbcd0-f164-44ff-a63e-77ce3df71043

2024-12-24 03:31 UTC, youngkidwarrior approved these changes

2024-12-24 08:31 UTC, merged