Move profile info state to url
0xsend/sendapp pull request #964
Opened 2024-12-22 14:00 UTC by musidlo

2024-12-23 02:17 UTC, youngkidwarrior requested changes

2024-12-23 02:17 UTC, youngkidwarrior commented on packages/app/routers/params.tsx
> +  isProfileInfoVisible?: boolean
let's keep booleans out of the url. 

It's an antipattern to show more than one modal at a time. Let's just make a state similar to `nav`, that uses a string enum


```suggestion
  modal?: "profile"
```

2024-12-23 06:45 UTC, musidlo commented on packages/app/routers/params.tsx
> +  isProfileInfoVisible?: boolean
applied

2024-12-24 09:53 UTC, musidlo commented
@youngkidwarrior rebased

2025-02-03 15:19 UTC, closed without merging