Redesign send confirmation
0xsend/sendapp pull request #969
Opened 2024-12-23 20:01 UTC by musidlo

2024-12-24 03:29 UTC, youngkidwarrior requested changes

2024-12-24 03:29 UTC, youngkidwarrior commented on packages/app/features/send/confirm/screen.tsx
> +            <AvatarProfile profile={profile} size={'$3'} mx="none" circular />
Lets use `<LinkableAvatar/>` here as well

2024-12-24 03:29 UTC, youngkidwarrior commented on packages/app/features/send/components/SendTopNav.tsx
> +                  return 'Recipient'
Designs are a little off here. Let's change this to Review Transfer and remove the other instance of it

2024-12-24 03:29 UTC, youngkidwarrior commented on packages/app/features/send/confirm/screen.tsx
> +          Review transfer
Remove this

2024-12-24 09:25 UTC, musidlo commented on packages/app/features/send/confirm/screen.tsx
> +            <AvatarProfile profile={profile} size={'$3'} mx="none" circular />
Applied

2024-12-24 09:26 UTC, musidlo commented on packages/app/features/send/components/SendTopNav.tsx
> +                  return 'Recipient'
applied what was discussed on qa channel

2024-12-24 09:26 UTC, musidlo commented on packages/app/features/send/confirm/screen.tsx
> +          Review transfer
Redesign send confirmation by musidlo · Pull Request #969 · 0xsend_sendapp

2024-12-29 22:20 UTC, youngkidwarrior commented
* **#969** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/969?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/969?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `dev`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-29 22:36 UTC, youngkidwarrior approved these changes

2024-12-29 22:36 UTC, youngkidwarrior commented
### Merge activity

* **Dec 29, 5:36 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/0xsend/sendapp/969).

2024-12-29 22:37 UTC, merged